[package]
name = "number-format"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
winnow = "0.7.10"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"